# Generated by Django 4.0.6 on 2022-07-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='ownner',
            new_name='owner',
        ),
    ]
